### ISSUE TITLE
Issues with variation within Switch/If statements

### ISSUE THREAD

**Issue by Carlshede** [benbehringer/peopl#10]
Trying to assign a piece of code in a switch/case statement to a feature moves that feature from the switch statement to above the switch. This is also true for creating new variation points within a switch statements.

This issue is present in both C and Java.

C:
1.
![switchissue](https://user-images.githubusercontent.com/8633105/53810344-029c1980-3f57-11e9-9c7d-46ef1f670f37.png)

2.
![switchissue2](https://user-images.githubusercontent.com/8633105/53810171-ac2edb00-3f56-11e9-989f-1371ceaada41.png)

3.
![switchissue3](https://user-images.githubusercontent.com/8633105/53810173-ac2edb00-3f56-11e9-8b6c-6f71b7fff8df.png)

Java:
1.
![switchissuejava](https://user-images.githubusercontent.com/8633105/53810174-ac2edb00-3f56-11e9-8d4c-f0c80d090102.png)

2.
![switchissuejava2](https://user-images.githubusercontent.com/8633105/53810175-acc77180-3f56-11e9-882d-30edbcf299a3.png)

3.
![switchissuejava3](https://user-images.githubusercontent.com/8633105/53810176-acc77180-3f56-11e9-933d-a2cdc2ae430d.png)

Tested in Windows & Linux.

EDIT: The same thing issue exists with if statements.

**Comment by Carlshede** [comment]
![screenshot 2019-03-05 at 16 19 44](https://user-images.githubusercontent.com/8633105/53816075-367d3c00-3f63-11e9-8864-ec7fc6bf7e4e.png)
![screenshot 2019-03-05 at 16 22 34](https://user-images.githubusercontent.com/8633105/53816076-367d3c00-3f63-11e9-8c9b-ed679ab4cc0f.png)

**Comment by benbehringer** [comment]
Yes, it works if there is at least one wrapper. Should work for blocks too.

**Comment by Carlshede** [comment]
There appears to be no issues with if or switch statements in the original release of PEoPL:
![originalpeopl](https://user-images.githubusercontent.com/8633105/53819513-59f7b500-3f6a-11e9-9821-8baecc738381.png)

**Comment by benbehringer** [comment]
Thanks for the pointer! Should be fixed now.
