### ISSUE TITLE
Unassigning a statement or merging a split block results in broken references

### ISSUE THREAD

**Issue by Carlshede** [benbehringer/peopl#15]
![unassignissuejava](https://user-images.githubusercontent.com/8633105/53973066-55fd9b80-4100-11e9-877d-5d8cac858e72.png)
![featuregroup](https://user-images.githubusercontent.com/8633105/53973235-ae349d80-4100-11e9-981d-e3df8e6b180d.png)

**Comment by benbehringer** [comment]
This is related to issue #6. The merge removes base code blocks and the checker complains about unresolved FeatureGroupReferences.
