### ISSUE TITLE
Alternative return types cause an exception

### ISSUE THREAD

**Issue by benbehringer** [benbehringer/peopl#2]
When creating an alternative return type the editor breaks.

<img width="595" alt="screenshot 2019-02-24 at 19 07 57" src="https://user-images.githubusercontent.com/37022575/53303168-8a9f6680-3867-11e9-9084-e55ec2655865.png">

**Comment by Carlshede** [comment]
This seems to be an issue wherever alternatives are used, e.g:

![localmethodcallinif](https://user-images.githubusercontent.com/8633105/53324295-ba3e8500-38e0-11e9-9841-c00f0eb8d69c.png)
or

![localmethodcallreal](https://user-images.githubusercontent.com/8633105/53324302-bd397580-38e0-11e9-91c4-0f03060b1eda.png)

**Comment by benbehringer** [comment]
Appearance seems to be fixed, yet still an issue with replacing the original node (e.g., the return type). To reproduce:
 i) create an alternative return type
 ii) change the return type we created an alternative for
=> the alternative is accidentally removed

**Comment by benbehringer** [comment]
Will create a new issue for the substitute issue described above
