### ISSUE TITLE
Split Block intention missing in Universal and Pre-Processor views

### ISSUE THREAD

**Issue by Carlshede** [benbehringer/peopl#9]
In the Colored Annotative view, the following Intentions are available:
![missingintention2](https://user-images.githubusercontent.com/8633105/53809610-67ef0b00-3f55-11e9-94dc-75c7447eb39f.png)

When switching to other projections, the Split Block intention is missing:
![missingintention1](https://user-images.githubusercontent.com/8633105/53809609-67ef0b00-3f55-11e9-852f-b1c84d3c2317.png)
![missingintention3](https://user-images.githubusercontent.com/8633105/53809612-67ef0b00-3f55-11e9-9b3b-f6b2d8d97c42.png)

Tested on Windows & Linux.

**Comment by benbehringer** [comment]
Great work! Thanks!
